<?php
/**
 * SMS Gateway — One-click Web Installer
 * ---------------------------------------------------------------
 * Step 0: preflight   Step 1: configuration form   Step 2: install
 * After a successful install this directory is auto-locked; delete it
 * for good measure. Requires PHP 8.1+ and the mysqli extension.
 */

declare(strict_types=1);

define('INSTALL_ROOT', __DIR__);
define('APP_ROOT', dirname(INSTALL_ROOT));
define('LOCK_FILE', INSTALL_ROOT . '/_lock');
define('ENV_FILE', APP_ROOT . '/.env');
define('SCHEMA_FILE', APP_ROOT . '/database/schema.sql');

// Already installed -> refuse to run again.
if (is_file(LOCK_FILE)) {
    http_response_code(403);
    echo '<!doctype html><html><head><meta charset="utf-8"><title>Locked</title></head><body style="font-family:system-ui;padding:40px">'
        . '<h1>Installation locked</h1><p>This application is already installed. Delete <code>install/_lock</code> only if you intend to reinstall (this will wipe the database).</p></body></html>';
    exit;
}

session_start();
$step = (int) ($_POST['step'] ?? ($_GET['step'] ?? 0));
$errors = [];
$success = '';

// ---------------------------------------------------------------- helpers
function env_escape(string $v): string
{
    // Escape value for a simple KEY=VALUE .env file.
    if (preg_match('/[^A-Za-z0-9 _.\\-\\/:@]/', $v)) {
        return '"' . str_replace(['\\\\', '"'], ['\\\\\\\\', '\\"'], $v) . '"';
    }
    return $v;
}

function checkPreflight(): array
{
    $problems = [];
    if (PHP_VERSION_ID < 80100) {
        $problems[] = 'PHP 8.1+ required (you have ' . PHP_VERSION . ').';
    }
    foreach (['mysqli', 'mbstring', 'openssl', 'json', 'curl', 'zip'] as $ext) {
        if (!extension_loaded($ext)) {
            $problems[] = "PHP extension <code>$ext</code> is not enabled.";
        }
    }
    if (!is_writable(APP_ROOT) && !is_writable(ENV_FILE)) {
        $problems[] = 'The application directory must be writable so we can create <code>.env</code>.';
    }
    if (!is_file(SCHEMA_FILE)) {
        $problems[] = 'Schema file <code>database/schema.sql</code> is missing.';
    }
    if (!class_exists('mysqli')) {
        $problems[] = 'mysqli class unavailable.';
    }
    return $problems;
}

function runInstall(array $p): array
{
    $errs = [];
    // 1) connect
    $mysqli = @new mysqli($p['db_host'], $p['db_user'], $p['db_pass'], $p['db_name'], (int) $p['db_port']);
    if ($mysqli->connect_error) {
        return ['Cannot connect to MySQL: ' . $mysqli->connect_error];
    }
    $mysqli->set_charset('utf8mb4');

    // 2) import schema
    $sql = @file_get_contents(SCHEMA_FILE);
    if ($sql === false) {
        return ['Cannot read schema file.'];
    }
    // Split on ; that is followed by newline (statement boundary) to be safe.
    $statements = preg_split('/;\\s*\\n/', $sql);
    foreach ($statements as $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '' || str_starts_with($stmt, '--') || str_starts_with($stmt, 'SET ')) {
            // still execute SET statements
            if (str_starts_with($stmt, 'SET ')) {
                $mysqli->query($stmt);
            }
            continue;
        }
        if (!$mysqli->query($stmt)) {
            $errs[] = 'SQL error: ' . $mysqli->error . ' — in: ' . substr($stmt, 0, 80);
        }
    }
    if ($errs) {
        return $errs;
    }

    // 3) seed admin user (bcrypt)
    $email = $mysqli->real_escape_string(strtolower(trim($p['admin_email'])));
    $hash = password_hash($p['admin_pass'], PASSWORD_BCRYPT, ['cost' => 12]);
    $name = $mysqli->real_escape_string(trim($p['admin_name']));
    $apiKey = bin2hex(random_bytes(24));
    $tz = $mysqli->real_escape_string($p['timezone']);
    $mysqli->query("INSERT INTO `User` (`name`,`email`,`password`,`isAdmin`,`apiKey`,`dateAdded`,`timeZone`,`credits`)
        VALUES ('$name','$email','$hash',1,'$apiKey',NOW(),'$tz',NULL)");

    // 4) write .env
    $env = [
        'APP_ENV' => 'production',
        'APP_SECRET_KEY' => bin2hex(random_bytes(32)),
        'APP_SESSION_NAME' => 'SMS_GATEWAY',
        'DB_SERVER' => $p['db_host'],
        'DB_PORT' => (string) $p['db_port'],
        'DB_USER' => $p['db_user'],
        'DB_PASS' => $p['db_pass'],
        'DB_NAME' => $p['db_name'],
        'TIMEZONE' => $p['timezone'],
        'FORCE_HTTPS' => $p['force_https'] ? 'true' : 'false',
        'TRUSTED_PROXIES' => $p['trusted_proxies'],
        'ALLOWED_HOSTS' => $p['allowed_hosts'],
        'LOGIN_MAX_ATTEMPTS' => '5',
        'LOGIN_LOCKOUT_SECONDS' => '900',
    ];
    $out = "# SMS Gateway environment — generated by the installer. Do not commit.\n";
    foreach ($env as $k => $v) {
        $out .= $k . '=' . env_escape($v) . "\n";
    }
    if (@file_put_contents(ENV_FILE, $out) === false) {
        return ['Could not write <code>.env</code>. Check directory permissions.'];
    }
    @chmod(ENV_FILE, 0600);

    // 5) lock the installer
    @file_put_contents(LOCK_FILE, date('c'));
    return [];
}

// ---------------------------------------------------------------- dispatch
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $p = [
        'db_host' => trim($_POST['db_host'] ?? 'localhost'),
        'db_port' => trim($_POST['db_port'] ?? '3306'),
        'db_user' => trim($_POST['db_user'] ?? ''),
        'db_pass' => $_POST['db_pass'] ?? '',
        'db_name' => trim($_POST['db_name'] ?? ''),
        'admin_name' => trim($_POST['admin_name'] ?? 'Administrator'),
        'admin_email' => trim($_POST['admin_email'] ?? ''),
        'admin_pass' => $_POST['admin_pass'] ?? '',
        'admin_pass2' => $_POST['admin_pass2'] ?? '',
        'timezone' => trim($_POST['timezone'] ?? 'UTC'),
        'force_https' => !empty($_POST['force_https']),
        'trusted_proxies' => trim($_POST['trusted_proxies'] ?? ''),
        'allowed_hosts' => trim($_POST['allowed_hosts'] ?? ''),
    ];
    if (!filter_var($p['admin_email'], FILTER_VALIDATE_EMAIL)) {
        $errors[] = 'A valid admin email is required.';
    }
    if (strlen($p['admin_pass']) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }
    if ($p['admin_pass'] !== $p['admin_pass2']) {
        $errors[] = 'Passwords do not match.';
    }
    if (empty($p['db_host']) || empty($p['db_user']) || empty($p['db_name'])) {
        $errors[] = 'Database host, user and name are required.';
    }
    if (!$errors) {
        $res = runInstall($p);
        if ($res) {
            $errors = array_merge($errors, $res);
        } else {
            $success = 'Installed successfully.';
        }
    }
}

// ---------------------------------------------------------------- view
$problems = ($step === 0) ? checkPreflight() : [];
$tzList = DateTimeZone::listIdentifiers();
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SMS Gateway — Installer</title>
<style>
  :root{--bg:#0f172a;--card:#1e293b;--accent:#22c55e;--txt:#e2e8f0;--mut:#94a3b8;--err:#f87171}
  *{box-sizing:border-box}
  body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:var(--bg);color:var(--txt);min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}
  .card{background:var(--card);border-radius:16px;padding:32px;width:100%;max-width:620px;box-shadow:0 20px 60px rgba(0,0,0,.4)}
  h1{margin:0 0 4px;font-size:22px}
  p.sub{margin:0 0 20px;color:var(--mut);font-size:14px}
  label{display:block;font-size:13px;margin:14px 0 6px;color:var(--mut)}
  input,select{width:100%;padding:11px 12px;border-radius:9px;border:1px solid #334155;background:#0f172a;color:var(--txt);font-size:14px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
  .btn{margin-top:22px;width:100%;padding:13px;border:0;border-radius:10px;background:var(--accent);color:#052e16;font-weight:700;font-size:15px;cursor:pointer}
  .err{background:rgba(248,113,113,.12);border:1px solid var(--err);color:var(--err);padding:12px 14px;border-radius:9px;font-size:13px;margin-bottom:16px}
  .ok{background:rgba(34,197,94,.12);border:1px solid var(--accent);color:var(--accent);padding:12px 14px;border-radius:9px;font-size:14px;margin-bottom:16px}
  .step{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--accent);margin-bottom:6px}
  ul{margin:8px 0;padding-left:18px;font-size:13px;color:var(--mut)}
  code{background:#0f172a;padding:1px 5px;border-radius:4px;color:#fbbf24}
  a{color:var(--accent)}
</style>
</head>
<body>
<div class="card">
<?php if ($success): ?>
  <div class="step">Done</div>
  <h1>🎉 SMS Gateway installed</h1>
  <p class="sub">Your gateway is ready. For security, delete the <code>install/</code> folder now.</p>
  <div class="ok"><?= htmlspecialchars($success) ?></div>
  <a class="btn" href="../login.php" style="display:block;text-align:center;text-decoration:none">Go to Login</a>
<?php else: ?>
  <div class="step">Step <?= $step + 1 ?> of 3</div>
  <h1>SMS Gateway Installer</h1>
  <p class="sub">Self-hosted SMS gateway — send & receive SMS from your Android device.</p>

  <?php if ($errors): ?><div class="err"><?php foreach ($errors as $e): ?>• <?= $e ?><br><?php endforeach; ?></div><?php endif; ?>

  <?php if ($step === 0): ?>
    <?php if ($problems): ?>
      <div class="err"><b>Preflight found issues:</b><br><?php foreach ($problems as $p): ?>• <?= $p ?><br><?php endforeach; ?></div>
      <p class="sub">Fix the above and reload this page.</p>
    <?php else: ?>
      <div class="ok">All system requirements passed. Click continue.</div>
      <form method="post"><input type="hidden" name="step" value="1"><button class="btn">Continue</button></form>
    <?php endif; ?>

  <?php elseif ($step === 1): ?>
    <form method="post">
      <input type="hidden" name="step" value="2">
      <label>Database host</label><input name="db_host" value="localhost" required>
      <div class="grid">
        <div><label>Port</label><input name="db_port" value="3306"></div>
        <div><label>Database name</label><input name="db_name" required></div>
      </div>
      <label>Database user</label><input name="db_user" required>
      <label>Database password</label><input type="password" name="db_pass">
      <hr style="border-color:#334155;margin:20px 0">
      <label>Admin name</label><input name="admin_name" value="Administrator">
      <label>Admin email</label><input type="email" name="admin_email" required>
      <div class="grid">
        <div><label>Password</label><input type="password" name="admin_pass" required></div>
        <div><label>Confirm</label><input type="password" name="admin_pass2" required></div>
      </div>
      <label>Default timezone</label>
      <select name="timezone"><?php foreach ($tzList as $tz): ?><option <?= $tz==='UTC'?'selected':'' ?>><?= $tz ?></option><?php endforeach; ?></select>
      <label><input type="checkbox" name="force_https" style="width:auto;margin-right:8px">Force HTTPS links</label>
      <label>Trusted proxies (comma-separated IPs, optional)</label><input name="trusted_proxies" placeholder="e.g. 10.0.0.1">
      <label>Allowed hosts (comma-separated, optional — leave empty to allow server name only)</label><input name="allowed_hosts" placeholder="smsgateway.example.com">
      <button class="btn">Install</button>
    </form>

  <?php endif; ?>
<?php endif; ?>
</div>
</body>
</html>